### ISSUE TITLE
Please consider adding a license

### ISSUE THREAD

**Issue by heuermh** [amcrisan/GEViTAnalysisRelease#1]
"[W]ithout a license, default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. "

See
https://help.github.com/en/articles/licensing-a-repository

**Comment by amcrisan** [comment]
Thanks for pointing this out! I didn't realize I had not added a license. I've now added an MIT license.

**Comment by heuermh** [comment]
Great!  Thank you, @amcrisan
